Traceback (most recent call last):
  File "/home/laser/miniconda3/envs/revamp/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/laser/miniconda3/envs/revamp/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laser/miniconda3/envs/revamp/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 168, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laser/miniconda3/envs/revamp/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/laser/miniconda3/envs/revamp/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/laser/miniconda3/envs/revamp/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/laser/miniconda3/envs/revamp/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
import ms3
import pandas as pd
from git import Repo

from utils import cnt, print_heading, resolve_dir, get_repo_name, remove_none_labels, remove_non_chord_labels

pd.options.display.max_columns = 50
pd.options.display.max_rows = 100
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[1], line 6[0m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mgit[39;00m [38;5;28;01mimport[39;00m Repo
[0;32m----> 6[0m [38;5;28;01mfrom[39;00m [38;5;21;01mutils[39;00m [38;5;28;01mimport[39;00m cnt, print_heading, resolve_dir, get_repo_name, remove_none_labels, remove_non_chord_labels
[1;32m      8[0m pd[38;5;241m.[39moptions[38;5;241m.[39mdisplay[38;5;241m.[39mmax_columns [38;5;241m=[39m [38;5;241m50[39m
[1;32m      9[0m pd[38;5;241m.[39moptions[38;5;241m.[39mdisplay[38;5;241m.[39mmax_rows [38;5;241m=[39m [38;5;241m100[39m

[0;31mImportError[0m: cannot import name 'cnt' from 'utils' (/home/laser/git/coup/notebooks/utils.py)

